Repository ivandi1980/id-spring-jwt, pull requests merged in 2022-06, with the labels that each got.

#1 added user & role on domain
  src/main/java/ivandjoh/jwt/domain/AppRole.java
  src/main/java/ivandjoh/jwt/domain/AppUser.java
Labels: enhancement

#2 created repositories for User & Role
  src/main/java/ivandjoh/jwt/repository/AppRoleRepository.java
  src/main/java/ivandjoh/jwt/repository/AppUserRepository.java
Labels: enhancement

#3 added dependencies injections on the services
  src/main/java/ivandjoh/jwt/repository/AppRoleRepository.java
  src/main/java/ivandjoh/jwt/repository/AppUserRepository.java
  src/main/java/ivandjoh/jwt/service/UserService.java
  src/main/java/ivandjoh/jwt/service/impl/UserServiceImpl.java
Labels: enhancement

#4 added the Service Implementation
  src/main/java/ivandjoh/jwt/service/impl/UserServiceImpl.java
Labels: enhancement

#6 added commandline runner
  src/main/java/ivandjoh/jwt/SpringSecurityJwtApplication.java
  src/main/java/ivandjoh/jwt/api/UserResourceController.java
  src/main/resources/application.properties
Labels: enhancement

#7 added security config
  src/main/java/ivandjoh/jwt/SpringSecurityJwtApplication.java
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/service/impl/UserServiceImpl.java
Labels: enhancement

#8 added custom authentication filter
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthenticationFilter.java
Labels: enhancement

#10 refactoring the custom Authentication Filter
  src/main/java/ivandjoh/jwt/SpringSecurityJwtApplication.java
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthenticationFilter.java
  src/main/java/ivandjoh/jwt/service/impl/UserServiceImpl.java
Labels: bug, enhancement, good first issue

#11 added Custom Authorization Filter
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthenticationFilter.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthorizationFilter.java
Labels: enhancement

#12 implemented the refresh token
  src/main/java/ivandjoh/jwt/api/UserResourceController.java
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthorizationFilter.java
Labels: enhancement

#13 updated Security Config
  src/main/java/ivandjoh/jwt/config/SecurityConfig.java
  src/main/java/ivandjoh/jwt/filter/CustomAuthorizationFilter.java
Labels: enhancement

#14 added postman collections
  SPRING PROJECT JWT.postman_collection.json
Labels: documentation, enhancement
